from multiprocessing import Process           # chama apenas a funçao Process do pacote multiprocessing...

def f(name):
  print('hello', name)

if __name__ == '__main__':
  p = Process(target=f, args=('bob filho', )) # primeiro processo...

  print('hello', 'bob pai')                   # segundo processo (processo original)...

  p.start()                                   # iniciar o processo...
  p.join()                                    # juntar os process (para esperar cada processo terminar e depois juntar todos) 

# Note que temos 2 processos...
# Função Process cria um novo processo (um processo apenas)...
# Target = destino é executar a funçao f...
